### ISSUE TITLE
Testsuite fails on some architectures (arm64 and ppc64el)

### ISSUE THREAD

**Issue by daissi** [wilkelab/isoband#10]
Hi,
The testsuite fails on some architectures (at least on arm64 and ppc64el) as you can see [here](https://ci.debian.net/packages/r/r-cran-isoband/).

```
> library(testthat)
> library(isoband)
> 
> test_check("isoband")
── 1. Failure: Catch unit tests pass (@test-cpp.R#3)  ──────────────────────────
C++ unit tests:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 is a Catch v1.9.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
Crop to unit box | test-clip-lines.cpp
  Double intersections
-------------------------------------------------------------------------------
test-clip-lines.cpp:176
...............................................................................

test-clip-lines.cpp:212: FAILED:
  CATCH_CHECK( result == in_middle )
with expansion:
  0 == 4

test-clip-lines.cpp:213: FAILED:
  CATCH_CHECK( near_equal(crop1.x, 0) )
with expansion:
  false

test-clip-lines.cpp:214: FAILED:
  CATCH_CHECK( near_equal(crop1.y, 0) )
with expansion:
  false

test-clip-lines.cpp:215: FAILED:
  CATCH_CHECK( near_equal(crop2.x, 1) )
with expansion:
  false

test-clip-lines.cpp:216: FAILED:
  CATCH_CHECK( near_equal(crop2.y, 1) )
with expansion:
  false

===============================================================================
test cases:   5 |   4 passed | 1 failed
assertions: 290 | 285 passed | 5 failed


══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 173 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
1. Failure: Catch unit tests pass (@test-cpp.R#3) 

Error: testthat unit tests failed
```

Best,
Dylan

**Comment by clauswilke** [comment]
This is frustrating. The C++ libraries I'm using have slight differences in behavior on different architectures and it has been difficult to put together a test suite that doesn't randomly fail. Apparently I missed some issues.

Do you have access to these architectures? If I propose a fix, could you try it on these machines to see if it worked?

**Comment by clauswilke** [comment]
This is the test case that seems to be failing:
https://github.com/wilkelab/isoband/blob/fc457a4cb44e2fe241355673fd1e9cfa03727dc4/src/test-clip-lines.cpp#L210-L216

**Comment by daissi** [comment]
> Do you have access to these architectures? If I propose a fix, could you try it on these machines to see if it worked?

Sure, I have access to all Debian portexbox.

**Comment by clauswilke** [comment]
Actually, what seems to be happening here is that the test code correctly shows that the implementation completely fails on these architectures. This is more troubling than an unstable test. It's also in a function that does just basic floating-point arithmetic. I'll have to think about what may be causing this.

**Comment by clauswilke** [comment]
Could you try the latest development version? I rewrote the clipping code to be more resilient against numerical instabilities. The unit tests should pass now.

**Comment by daissi** [comment]
> Could you try the latest development version? I rewrote the clipping code to be more resilient against numerical instabilities. The unit tests should pass now.

Tested on arm64 and ppc64el and I confirm the unit tests pass now! Thanks! :-)

**Comment by clauswilke** [comment]
Super, thanks. I'll see if I can release a new version within the next few days.

**Comment by clauswilke** [comment]
On CRAN now. Thanks for reporting this.
