### ISSUE TITLE
Install isoband

### ISSUE THREAD

**Issue by jialiwang1211** [wilkelab/isoband#13]
Hi, 

I was trying to install isoband but got the following error message. Any help would be appreciated!

########################################################
Selection: 1
trying URL 'https://cloud.r-project.org/src/contrib/isoband_0.2.2.tar.gz'
Content type 'application/x-gzip' length 2295931 bytes (2.2 MB)

downloaded 2.2 MB

* installing *source* package ‘isoband’ ...
** package ‘isoband’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/modules/EasyBuild/software/R/3.6.1/lib64/R/include" -DNDEBUG  -I"/gpfs/fs1/modules/EasyBuild/software/R/3.6.1/lib64/R/library/testthat/include" -I/usr/local/include  -fpic  -g -O2  -c clip-lines.cpp -o clip-lines.o
In file included from clip-lines.cpp:12:0:
utils.h:28:1: error: expected unqualified-id before ‘[’ token
make: *** [clip-lines.o] Error 1
ERROR: compilation failed for package ‘isoband’
* removing ‘/gpfs/fs1/home/jwang/R/x86_64-pc-linux-gnu-library/3.6/isoband’

The downloaded source packages are in
	‘/tmp/RtmpOc7LSs/downloaded_packages’
Warning messages:
1: In download.file(url, destfile = f, quiet = TRUE) :
  URL 'https://cran.r-project.org/CRAN_mirrors.csv': status was 'Peer certificate cannot be authenticated with given CA certificates'
2: In install.packages("isoband") :
  installation of package ‘isoband’ had non-zero exit status

**Comment by clauswilke** [comment]
Your compiler is too old. You need a compiler that supports the C++11 standard.
