### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by windtalker6** [wilkelab/isoband#14]
when I tried to install this package by:

install.packages('isoband')

the error was:
===================================

> /XXXX/gcc/include/c++/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

===================================

Someone suggested adding “-std=c++11“ or “-std=gnu++11”  to the g++ command line. 

however, I started by 'install.packages('isoband')', and find no arguments in install.packages() to add any parameter to g++.

how can I solve this?

**Comment by clauswilke** [comment]
See #12, #13.
