### ISSUE TITLE
special contour isoline

### ISSUE THREAD

**Issue by fipoucat** [wilkelab/isoband#15]
Hello,

 I am attempting to plot seal level pressure (isobars) contour o an spatial area with 2mb spacing and want a specific isobar (1015) plotted as thicker line than the others and wonder if it is possible with isoband or other with ggplot related function.
Below the command I sued to plot the isobar. Now any idea on haw to add a oommand for the 1015 isobar?

syn_plot <- ggplot() + 
  geom_tile(data = synclas_gather_df, aes(x=x, y=y, fill=value)) +
  geom_sf(data = map_bg, fill="transparent")+
  geom_contour2(data = synclas_gather_df, aes(x=x,y=y,z=value), binwidth = 2, color = "black") +
  scale_fill_gradientn(colours = colorRamps::matlab.like2(100), name = "hPa",breaks=0:5) + 
  scale_colour_gradient(guide = 'none') + facet_wrap(~key, ncol = 4) +
  scale_x_continuous(limits = c(-34,29), expand = c(0, 0))+
  scale_y_continuous(limits = c(-9,34), expand = c(0,0))+
  theme_bw() + theme(axis.title = element_blank(), 
                     axis.text = element_blank(),
                     axis.ticks = element_blank())

syn_plot + geom_text_contour(data= synclas_gather_df,aes(x,y,z = value), stroke = 0.10,binwidth = 4,size=3)

**Comment by clauswilke** [comment]
This type of question (user support for a downstream package) is not appropriate for the isoband issue tracker. You could ask on stackoverflow or on the RStudio Community Forums.
