### ISSUE TITLE
Drop run-time dependency on testthat

### ISSUE THREAD

**Issue by hadley** [wilkelab/isoband#19]
I think the easiest way to do this is to just copy the testthat headers into isoband, rather than using LinkingTo.  

This is worth doing so that ggplot2 doesn't require testthat and all its dependencies to be installed.

**Comment by clauswilke** [comment]
Happy to approve a PR that accomplishes this.

**Comment by hadley** [comment]
Fixed by #20.

@clauswilke do you mind planning a release in the not-too-distant future?

**Comment by clauswilke** [comment]
Yes, will do it in the next few days. There hasn't been any other development since the last CRAN submission, so it should be straightforward. (Famous last words.)

I'll keep this issue open until it's on CRAN.

**Comment by clauswilke** [comment]
On CRAN now.
