### ISSUE TITLE
Build fails with newest glibc

### ISSUE THREAD

**Issue by Enchufa2** [wilkelab/isoband#25]
Same issue as https://github.com/r-lib/testthat/issues/1373, because you include the source of testthat in this package: `SIGSTKSZ` is not a constant anymore. You can check e.g. in Fedora rawhide.

**Comment by clauswilke** [comment]
@Enchufa2 Thanks for letting us know.

@hadley @jimhester Can somebody from the tidyverse team take this on? As a reminder, we vendored the testthat code here to remove the indirect dependency of ggplot2 on testthat.

**Comment by clauswilke** [comment]
Looks like it's just a matter of updating the catch code to the latest release.

**Comment by clauswilke** [comment]
@jimhester I saw your comment in the testthat repo about Catch1 vs Catch2. Would it make sense here to switch to Catch2? isoband already requires C++11.

**Comment by jimhester** [comment]
No, I think I would probably just use the same fix here as in https://github.com/r-lib/testthat/pull/1403

**Comment by clauswilke** [comment]
Sounds good to me, thanks!

**Comment by clauswilke** [comment]
@Enchufa2 Could you try with the latest development version? This should be fixed now. If it looks good on your end I'll release a patch version soon.

**Comment by Enchufa2** [comment]
LGTM!
