### ISSUE TITLE
Adding release for `0.2.5` on GitHub

### ISSUE THREAD

**Issue by MKyhos** [wilkelab/isoband#30]
Hello dear maintainers,
if you find time, could you kindly add the release for the `0.2.5` also on GitHub (as it is already available on CRAN).

Thank you very much and have a great day! :bouquet:

**Comment by clauswilke** [comment]
Done now.

**Comment by MKyhos** [comment]
Thank you so much @clauswilke, and I really hope you can enjoy the rest the weekend and next days! :pray:
