### ISSUE TITLE
Compilation error for LLVM clang 15.0.0

### ISSUE THREAD

**Issue by clauswilke** [wilkelab/isoband#31]
The isoband package doesn't compile under LLVM clang 15.0.0. There's some additional info here: 
https://www.stats.ox.ac.uk/pub/bdr/clang15/

I'm not sure I understand exactly what the problem is, but it seems it stems from headers copied from testthat, so whatever the fix for testthat is would have to be replicated for isoband. And looking a little more carefully, it's probably related to the Catch unit testing framework.

cc @hadley @thomasp85

**Comment by hadley** [comment]
@kevinushey might have more ideas

**Comment by kevinushey** [comment]
I'll take a look!

**Comment by kevinushey** [comment]
Looks like an incompatibility of the bundled version of Catch with LLVM 15. As a workaround, you could set:

```
-DCATCH_CONFIG_CPP11_NO_SHUFFLE
```

as part of your `PKG_CPPFLAGS`. I'll see if I can patch Catch for testthat as well.

**Comment by clauswilke** [comment]
Thanks! Looks like a reasonably simple fix.

As an aside, is isoband the only package that even uses this C++-based testing framework? I feel this is the second time that isoband breaks because of a Catch issue, and each time isoband and testthat seem to be the only packages affected. Makes me wonder whether it'd be better to rewrite the tests so they don't require a framework.

**Comment by kevinushey** [comment]
There are a few others, but overall C++ unit testing via Catch with testthat does not appear to be super popular.

**Comment by Helmut01** [comment]
If I counted correctly, 4,476 packages are affected. That’s ≈25% [sic] of all packages on CRAN.

**Comment by clauswilke** [comment]
Fixed and on CRAN.

**Comment by kevinushey** [comment]
Thanks @clauswilke, and sorry for all the grief this has caused 😞
