### ISSUE TITLE
Impending CRAN archival concerns hundrets of R packages

### ISSUE THREAD

**Issue by kapsner** [wilkelab/isoband#32]
Hello  @clauswilke ,

As todays email from Prof. Brian Ripley states, the yet unsolved [CRAN issues of `isoband`](https://cran.r-project.org/web/checks/check_results_isoband.html) lead to an impending CRAN archival of `isoband` and its strong reverse dependencies:

> CRAN package isoband and its reverse dependencies
> ....
> We have asked for an update fixing the check problems shown at
  <https://cran.r-project.org/web/checks/check_results_isoband.html>
with no update from the maintainer thus far.
Thus, package isoband is now scheduled for archival on 2022-10-19, and
archiving this will necessitate also archiving its CRAN strong reverse
dependencies.

As `ggplot2` directly depends on `isobands`, this impending archival on CRAN concerns hundrets of R packages which import `ggplot2`. 

Is it possible to have these issues fixed in time to avoid having so many packages be affected by a potential archiving of `isobands` on CRAN.

Alternatively, I have suggested [here](https://github.com/tidyverse/ggplot2/issues/5006) to remove `isoband` as a strong dependency of `ggoplot2` as kind of a "fallback-solution".

**Comment by clauswilke** [comment]
#31

**Comment by tbates** [comment]
might make sense to leave one of these open so we aren't each thinking there is no understanding of the issue here,
