### ISSUE TITLE
isoband update to avoid archiving (appears to be in-hand, this just documents it for affected parties)

### ISSUE THREAD

**Issue by tbates** [wilkelab/isoband#33]
A few hundred of us got an email that `isoband` would be archived on 19 October if it was not updated to pass CRAN checks (also affecting packages which have it as a dependency).

The cran result is here:  <https://cran.r-project.org/web/checks/check_results_isoband.html>

**Comment by clauswilke** [comment]
Yes, I need to copy some header files from testthat to fix a compilation error that will become a problem soon. I don't have an easy way to test the fix, so I'll have to proceed on faith that testthat contains the right fix, and for that reason I was waiting a bit to see if testthat was making it to CRAN safely. That hasn't happened yet.

If somebody can reproduce the error and is willing to test the development version of isoband let me know. I'll copy the files over from testthat some time later today.

**Comment by clauswilke** [comment]
This should now be fixed on github. Again, if somebody could confirm that things now work for LLVM clang 15.0.0 that would be great.

**Comment by clauswilke** [comment]
Resolved now.
