### ISSUE TITLE
CRAN Archiving Message

### ISSUE THREAD

**Issue by davidaarmstrong** [wilkelab/isoband#34]
This e-mail was sent to the maintainers of more than 1000 packages that have isoband as a dependency (mine included). 

>We have asked for an update fixing the check problems shown at
>  <https://cran.r-project.org/web/checks/check_results_isoband.html>
>with no update from the maintainer thus far.
>
>Thus, package isoband is now scheduled for archival on 2022-10-19, and
>archiving this will necessitate also archiving its CRAN strong reverse
>dependencies.

Could you please address the CRAN check problems and resubmit to prevent your package (and all of our packages) from being archived?

**Comment by tbates** [comment]
let's not duplicate issues for Claus. he is aware of the issue (links in #33 and process for fixing in https://github.com/tidyverse/ggplot2/issues/5006 ) and #31

**Comment by davidaarmstrong** [comment]
Apologies, I'll close this issue, then.
