### ISSUE TITLE
Testthat CRAN issues

### ISSUE THREAD

**Issue by clauswilke** [wilkelab/isoband#35]
We have again angered the CRAN gods:
```
On 11/12/2022 06:31, Prof Brian Ripley wrote:
> Dear maintainer,
> Please see the problems shown on https://cran.r-project.org/web/checks/check_results_isoband.html
> Please correct before 2023-01-09 to safely retain your package on CRAN.
> The CRAN Team

Your use of test-runner.cpp has again taken up our time.  If you are really convinced that it is essential for your package, use LinkingTo: testthat like everyone else and remove your copy of the faulty code.

In any case, correct before 2022-12-21 (and the winter shutdown) to retain your package on CRAN.
```

The testthat dependency was originally removed to make the ggplot2 stack lighter, see #19.

The problem is now an illegal symbol that has made it into the compiled code: https://cran.r-project.org/web/checks/check_results_isoband.html
This does not affect package function, and in fact the code only gets called during unit testing.

I'm getting quite tired of this. The simple solution is to disable all unit tests. The code has run fine for thousands of users, and it's quite stable, so maybe not running unit tests is the best way forward.

I am super busy the next week and don't think I can look into this before Dec. 17 the earliest.

cc @hadley @thomasp85

**Comment by yutannihilation** [comment]
It seems testthat already fixed the problem and was released on CRAN yesterday, so probably the warning will disappear?

c.f. https://github.com/r-lib/testthat/pull/1716

**Comment by thomasp85** [comment]
My opinion is to just remove unit testing on cran or remove the C++ unit testing and rely on R-level unit tests, whichever is the easiest

**Comment by clauswilke** [comment]
To be clear, the problem has always been the compilation of the testing code, so we can't just skip its execution on CRAN, we need to disable its compilation.

The C++ testing code consists of a bunch of low-level tests of various computations, such as that line intersections give the correct results. There are higher-level R unit tests also, and in fact most of the unit tests are written in R.

I'm comfortable disabling the C++ unit tests but I don't want to remove them from the repo entirely, in case at some point in the future something low-level goes wrong and the tests may be helpful to debug. I think I'll just comment out all the testing code and remove the vendored testthat code. That should be easy enough to do and I can try it within the next few days.

**Comment by hadley** [comment]
@clauswilke feel free to leave it and we can figure it out.

**Comment by clauswilke** [comment]
Let's resolve #36 first and then we can resolve this issue. If the decision is to disable the C++ test code (rather than going back to linking to testthat) then I can create that patch.

**Comment by thomasp85** [comment]
In favour of disabling the C++ test code

**Comment by clauswilke** [comment]
@thomasp85 Sounds good. I will prepare a PR.

**Comment by clauswilke** [comment]
Closed via https://github.com/wilkelab/isoband/commit/27eb847d26f2788c6bf61a0f75b1cf198b59d880
