### ISSUE TITLE
Showing "isolabels"

### ISSUE THREAD

**Issue by PMassicotte** [wilkelab/isoband#7]
Hi @clauswilke, thank you for this package.

I was wondering if it was possible to add labels of the isobands on the graph? Something like:

![image](https://user-images.githubusercontent.com/4519221/56140925-cf8f7180-5f69-11e9-90fa-95c94845a19d.png)
Regards,
Phil

**Comment by clauswilke** [comment]
I don't understand what exactly you're asking for. `isolines_grob()` provides the underlying technology for a plot like the one you show, but integration into actual plotting packages will have to be done by downstream packages.

**Comment by PMassicotte** [comment]
I was just trying to find out if there was an option/function to automatically add labels on the isobands. I will look at the `isolines_grob()`.

**Comment by clauswilke** [comment]
https://wilkelab.org/isoband/articles/isoband3.html
